---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes
- name: install python pip3
  apt:
    name:
      - python3-pip
      - nginx
      - net-tools
    state: present
  become: yes
- name: Set timezone to UTC
  shell: timedatectl set-timezone UTC
  args:
    executable: /bin/bash
  become: yes
